codecov:
  require_ci_to_pass: yes
  notify:
    wait_for_ci: yes
coverage:
  status:
    project:
      default:
        enabled: yes
        threshold: null
        target: auto
    patch:
      default:
        target: 60%
        threshold: 40%
